#!/bin/bash

tst () {
    echo
    echo $1 ' | ' $2
    echo $1 | ./ss
}

tst '1 2 3' '1'
tst '1A 16 10' '26'
tst '34 8 10' '28'
tst '1a 16 7' '35'
tst 'cc 13 16' 'A8'
tst '0 0 0' '!'
tst '0 12 45' '0'
tst '12 0 10' '!'
tst '12 10 0' '!'
tst '12 10 16' 'C'
